using UnityEngine;
using UnityEngine.UI;
using TMPro;
using GameLogic.Common;

namespace GameLogic
{
    public class SettingMenuBind : UIBindBase
    {
        public Image bg;
        public RectTransform transLayout;
        public Slider BGMVolume;
        public Image Background;
        public RectTransform Fill_Area;
        public Image Fill;
        public RectTransform Handle_Slide_Area;
        public Image Handle;
        public TextMeshProUGUI tmpBGM;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas;
        public TextMeshProUGUI tmpBGMVolume;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas1;
        public Slider SoundVolume;
        public Image Background1;
        public RectTransform Fill_Area1;
        public Image Fill1;
        public RectTransform Handle_Slide_Area1;
        public Image Handle1;
        public TextMeshProUGUI tmpSound;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas2;
        public TextMeshProUGUI tmpSoundVolume;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas3;
        public Slider UIVolume;
        public Image Background2;
        public RectTransform Fill_Area2;
        public Image Fill2;
        public RectTransform Handle_Slide_Area2;
        public Image Handle2;
        public TextMeshProUGUI tmpUI;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas4;
        public TextMeshProUGUI tmpUIVolume;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas5;
        public TextMeshProUGUI tmpCurLanguage;
        public Button btnLastLanguage;
        public Image Image;
        public Button btnNextLanguage;
        public Image Image1;
        public TextMeshProUGUI tmpCurDisplayMode;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas6;
        public Button btnLastDisplayMode;
        public Image Image2;
        public Button btnNextDisplayMode;
        public Image Image3;
        public TextMeshProUGUI tmpCurDisplayResolution;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas7;
        public Button btnLastDisplayResolution;
        public Image Image4;
        public Button btnNextDisplayResolution;
        public Image Image5;
        public RectTransform transFunBtnList;
        public Button btnCancel;
        public Image Image6;
        public TextMeshProUGUI tmpCancel;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas8;
        public Button btnConfirm;
        public Image Image7;
        public TextMeshProUGUI tmpConfirm;
        public RectTransform TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas9;

        public override void BindUI()
        {
            bg = GameObjectCommon.FindComponentWithName<Image>("bg", gameObject);
            transLayout = GameObjectCommon.FindComponentWithName<RectTransform>("transLayout", gameObject);
            BGMVolume = GameObjectCommon.FindComponentWithName<Slider>("BGMVolume", transLayout.gameObject);
            Background = GameObjectCommon.FindComponentWithName<Image>("Background", BGMVolume.gameObject);
            Fill_Area = GameObjectCommon.FindComponentWithName<RectTransform>("Fill Area", BGMVolume.gameObject);
            Fill = GameObjectCommon.FindComponentWithName<Image>("Fill", Fill_Area.gameObject);
            Handle_Slide_Area = GameObjectCommon.FindComponentWithName<RectTransform>("Handle Slide Area", BGMVolume.gameObject);
            Handle = GameObjectCommon.FindComponentWithName<Image>("Handle", Handle_Slide_Area.gameObject);
            tmpBGM = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpBGM", BGMVolume.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpBGM.gameObject);
            tmpBGMVolume = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpBGMVolume", BGMVolume.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas1 = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpBGMVolume.gameObject);
            SoundVolume = GameObjectCommon.FindComponentWithName<Slider>("SoundVolume", transLayout.gameObject);
            Background1 = GameObjectCommon.FindComponentWithName<Image>("Background", SoundVolume.gameObject);
            Fill_Area1 = GameObjectCommon.FindComponentWithName<RectTransform>("Fill Area", SoundVolume.gameObject);
            Fill1 = GameObjectCommon.FindComponentWithName<Image>("Fill", Fill_Area1.gameObject);
            Handle_Slide_Area1 = GameObjectCommon.FindComponentWithName<RectTransform>("Handle Slide Area", SoundVolume.gameObject);
            Handle1 = GameObjectCommon.FindComponentWithName<Image>("Handle", Handle_Slide_Area1.gameObject);
            tmpSound = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpSound", SoundVolume.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas2 = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpSound.gameObject);
            tmpSoundVolume = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpSoundVolume", SoundVolume.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas3 = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpSoundVolume.gameObject);
            UIVolume = GameObjectCommon.FindComponentWithName<Slider>("UIVolume", transLayout.gameObject);
            Background2 = GameObjectCommon.FindComponentWithName<Image>("Background", UIVolume.gameObject);
            Fill_Area2 = GameObjectCommon.FindComponentWithName<RectTransform>("Fill Area", UIVolume.gameObject);
            Fill2 = GameObjectCommon.FindComponentWithName<Image>("Fill", Fill_Area2.gameObject);
            Handle_Slide_Area2 = GameObjectCommon.FindComponentWithName<RectTransform>("Handle Slide Area", UIVolume.gameObject);
            Handle2 = GameObjectCommon.FindComponentWithName<Image>("Handle", Handle_Slide_Area2.gameObject);
            tmpUI = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpUI", UIVolume.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas4 = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpUI.gameObject);
            tmpUIVolume = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpUIVolume", UIVolume.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas5 = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpUIVolume.gameObject);
            tmpCurLanguage = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpCurLanguage", transLayout.gameObject);
            btnLastLanguage = GameObjectCommon.FindComponentWithName<Button>("btnLastLanguage", tmpCurLanguage.gameObject);
            Image = GameObjectCommon.FindComponentWithName<Image>("Image", btnLastLanguage.gameObject);
            btnNextLanguage = GameObjectCommon.FindComponentWithName<Button>("btnNextLanguage", tmpCurLanguage.gameObject);
            Image1 = GameObjectCommon.FindComponentWithName<Image>("Image", btnNextLanguage.gameObject);
            tmpCurDisplayMode = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpCurDisplayMode", transLayout.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas6 = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpCurDisplayMode.gameObject);
            btnLastDisplayMode = GameObjectCommon.FindComponentWithName<Button>("btnLastDisplayMode", tmpCurDisplayMode.gameObject);
            Image2 = GameObjectCommon.FindComponentWithName<Image>("Image", btnLastDisplayMode.gameObject);
            btnNextDisplayMode = GameObjectCommon.FindComponentWithName<Button>("btnNextDisplayMode", tmpCurDisplayMode.gameObject);
            Image3 = GameObjectCommon.FindComponentWithName<Image>("Image", btnNextDisplayMode.gameObject);
            tmpCurDisplayResolution = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpCurDisplayResolution", transLayout.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas7 = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpCurDisplayResolution.gameObject);
            btnLastDisplayResolution = GameObjectCommon.FindComponentWithName<Button>("btnLastDisplayResolution", tmpCurDisplayResolution.gameObject);
            Image4 = GameObjectCommon.FindComponentWithName<Image>("Image", btnLastDisplayResolution.gameObject);
            btnNextDisplayResolution = GameObjectCommon.FindComponentWithName<Button>("btnNextDisplayResolution", tmpCurDisplayResolution.gameObject);
            Image5 = GameObjectCommon.FindComponentWithName<Image>("Image", btnNextDisplayResolution.gameObject);
            transFunBtnList = GameObjectCommon.FindComponentWithName<RectTransform>("transFunBtnList", transLayout.gameObject);
            btnCancel = GameObjectCommon.FindComponentWithName<Button>("btnCancel", transFunBtnList.gameObject);
            Image6 = GameObjectCommon.FindComponentWithName<Image>("Image", btnCancel.gameObject);
            tmpCancel = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpCancel", btnCancel.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas8 = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpCancel.gameObject);
            btnConfirm = GameObjectCommon.FindComponentWithName<Button>("btnConfirm", transFunBtnList.gameObject);
            Image7 = GameObjectCommon.FindComponentWithName<Image>("Image", btnConfirm.gameObject);
            tmpConfirm = GameObjectCommon.FindComponentWithName<TextMeshProUGUI>("tmpConfirm", btnConfirm.gameObject);
            TMP_SubMeshUI_fusionpixel12pxproportionalzh_hans_SDF_Material__LiberationSans_SDF_Atlas9 = GameObjectCommon.FindComponentWithName<RectTransform>("TMP SubMeshUI [fusion-pixel-12px-proportional-zh_hans SDF Material + LiberationSans SDF Atlas]", tmpConfirm.gameObject);
        }
    }
}
